### ISSUE TITLE
Cant find the binance java sdk dependency

### ISSUE THREAD

**Issue by CuteCubed** [yonathan95/BinanceTradingBot#1]
Hi!
I'm unable to find your artifact with the name of com.github.yonathan95:binance-java-sdk:jar:1.0.0.

**Comment by yonathan95** [comment]
Hi,
Thank you for this comment!
I checked what caused it to happen, and the answer is that I made a mistake, apparently the package is not found in maven repository since it is a GitHub package. In order to solve this issue all you need to do is add the following lines to your ~/.m2/settings.xml:
<activeProfiles>
    <activeProfile>github</activeProfile>
</activeProfiles>

  <profiles>
    <profile>
      <id>github</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/yonathan95/*</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
    </profile>
</profiles>

  <servers>
    <server>
      <id>github</id>
      <username><your usename></username>
      <password><your github password token></password>
    </server>
</servers>
  

This will allow your maven to use this package. please let me know if it doesn't work out for you.

**Comment by yonathan95** [comment]
I also fixed the dependency in the Pom.xml so you should try updating it first.

**Comment by CuteCubed** [comment]
Thanks ! It worked fine!<3
